import {NextResponse} from "next/server";
import {createHash,randomBytes} from "node:crypto";
import {db} from "@/lib/db";
import {getWorkspaceId} from "@/lib/workspace";
import {limited,limitedResponse} from "@/lib/rate-limit";

export async function GET(){const workspaceId=await getWorkspaceId();const agents=await db.agent.findMany({where:{server:{workspaceId}},include:{server:{include:{metrics:{orderBy:{recordedAt:"desc"},take:1}}}},orderBy:{createdAt:"desc"}});const safe=agents.map(({tokenHash,...a})=>({...a,server:a.server?{...a.server,metrics:a.server.metrics.map(m=>({...m,uptimeSeconds:Number(m.uptimeSeconds)}))}:a.server}));return NextResponse.json(safe);}
export async function POST(req:Request){const rl=limited(req,"agents:create",10,60000);if(!rl.ok)return limitedResponse(rl);try{const workspaceId=await getWorkspaceId();const b=await req.json();const name=String(b.name||"").trim(),serverName=String(b.serverName||"").trim();if(!name||!serverName)return NextResponse.json({error:"name and serverName required"},{status:400});if(name.length>120||serverName.length>120)return NextResponse.json({error:"Name is too long"},{status:400});const token=randomBytes(32).toString("hex"),hash=createHash("sha256").update(token).digest("hex");const server=await db.server.create({data:{workspaceId,name:serverName,hostname:b.hostname||null}});const agent=await db.agent.create({data:{serverId:server.id,name,tokenHash:hash}});return NextResponse.json({agentId:agent.id,serverId:server.id,token,serverName:server.name,warning:"Store this token securely. It will not be shown again."},{status:201});}catch(e:any){return NextResponse.json({error:e?.message||"Unable to create agent"},{status:400});}}
export async function DELETE(req:Request){try{const rl=limited(req,"agents:delete",20,60000);if(!rl.ok)return limitedResponse(rl);const workspaceId=await getWorkspaceId();const id=new URL(req.url).searchParams.get("id");if(!id)return NextResponse.json({error:"id required"},{status:400});const existing=await db.agent.findFirst({where:{id,server:{workspaceId}},select:{id:true,serverId:true}});if(!existing)return NextResponse.json({error:"Agent not found"},{status:404});await db.$transaction(async tx=>{await tx.agent.delete({where:{id:existing.id}});await tx.server.delete({where:{id:existing.serverId}});});return NextResponse.json({ok:true});}catch(e:any){return NextResponse.json({error:e?.message||"Unable to delete agent"},{status:400});}}
