import Link from "next/link";
import {Activity,ArrowLeft,Globe2,Server,Database,AlertTriangle,ShieldCheck} from "lucide-react";

export default function About(){
 return <main className="min-h-screen bg-[#07090d] text-slate-100">
  <header className="border-b border-white/[.06]"><div className="mx-auto flex max-w-5xl items-center justify-between px-5 py-5"><Link href="/" className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-cyan-400/10 border border-cyan-400/20"><Activity className="text-cyan-300" size={19}/></div><span className="font-extrabold tracking-wide">SERVER MONITOR</span></Link><Link href="/" className="flex items-center gap-2 text-sm text-slate-400 hover:text-white"><ArrowLeft size={15}/> Home</Link></div></header>
  <div className="mx-auto max-w-5xl px-5 py-16">
   <div className="section-kicker">About the platform</div><h1 className="mt-3 text-4xl font-black sm:text-5xl">A practical monitoring layer for developers.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-400">SERVER MONITOR is designed to put websites, APIs, local services and infrastructure health into one clear dashboard. Its core purpose is reliable monitoring, not an AI chatbot.</p>
   <div className="mt-12 grid gap-5 md:grid-cols-2">
    <div className="card p-6"><Globe2 className="text-cyan-300" size={22}/><h2 className="mt-4 text-xl font-bold">Website & API checks</h2><p className="mt-2 text-sm leading-6 text-slate-400">The worker periodically sends HTTP/HTTPS requests and records availability, status code, status meaning, response time, timeout, DNS and TLS failures, SSL expiry and uptime history.</p></div>
    <div className="card p-6"><Server className="text-cyan-300" size={22}/><h2 className="mt-4 text-xl font-bold">Machine monitoring</h2><p className="mt-2 text-sm leading-6 text-slate-400">A lightweight agent can run on Windows, Linux, VPS or cloud machines and report CPU, RAM, disk, network, uptime, operating system, hostname and heartbeat information.</p></div>
    <div className="card p-6"><Database className="text-cyan-300" size={22}/><h2 className="mt-4 text-xl font-bold">Historical visibility</h2><p className="mt-2 text-sm leading-6 text-slate-400">Checks and metrics are stored so you can inspect recent health, response-time history, incidents and infrastructure trends instead of seeing only the current state.</p></div>
    <div className="card p-6"><AlertTriangle className="text-cyan-300" size={22}/><h2 className="mt-4 text-xl font-bold">Incidents & alerts</h2><p className="mt-2 text-sm leading-6 text-slate-400">When a service becomes unavailable, the system can create an incident and send supported email alerts. Recovery events and alert cooldowns help avoid unnecessary notification spam.</p></div>
   </div>
   <section className="mt-14"><div className="section-kicker">How the architecture works</div><h2 className="mt-3 text-3xl font-bold">Browser → worker → database → dashboard</h2>
    <div className="mt-7 grid gap-3 md:grid-cols-4">{[["1","Dashboard","You configure monitors and inspect results."],["2","Monitoring Worker","Checks continue on a schedule even when the browser is closed."],["3","PostgreSQL","Results, incidents, alerts and metrics are stored."],["4","Dashboard / Status Page","Current health and selected public status are displayed."]].map(([n,t,d])=><div key={n} className="card p-5"><div className="text-xs font-mono text-cyan-300">{n}</div><div className="mt-3 font-bold">{t}</div><p className="mt-2 text-xs leading-5 text-slate-400">{d}</p></div>)}</div>
   </section>
   <section className="mt-14 card overflow-hidden p-6 sm:p-8"><div className="section-kicker">Where your data lives</div><h2 className="mt-3 text-2xl font-bold sm:text-3xl">Anonymous browser identity, isolated workspace, PostgreSQL storage.</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-400">The browser keeps only the random anonymous ID needed to recognize the visitor. The actual monitoring data is stored server-side in PostgreSQL and scoped to that visitor's workspace.</p><div className="mt-8 grid items-center gap-4 sm:grid-cols-[1fr_auto_1fr_auto_1fr]"><div className="storage-node text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl border border-cyan-400/20 bg-cyan-400/10"><Server className="text-cyan-300" size={24}/></div><div className="mt-2 text-xs font-semibold">Browser</div><div className="text-[10px] text-slate-500">Anonymous ID</div></div><div className="storage-flow hidden sm:block"><span/><span/><span/></div><div className="storage-node text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl border border-violet-400/20 bg-violet-400/10"><ShieldCheck className="text-violet-300" size={24}/></div><div className="mt-2 text-xs font-semibold">Workspace</div><div className="text-[10px] text-slate-500">Isolated ownership</div></div><div className="storage-flow hidden sm:block"><span/><span/><span/></div><div className="storage-node text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl border border-emerald-400/20 bg-emerald-400/10"><Database className="text-emerald-300" size={24}/></div><div className="mt-2 text-xs font-semibold">PostgreSQL</div><div className="text-[10px] text-slate-500">Persistent history</div></div></div></section>
   <section className="mt-14 card p-6 sm:p-8"><div className="flex items-start gap-4"><ShieldCheck className="mt-1 shrink-0 text-emerald-300" size={23}/><div><h2 className="text-xl font-bold">Security and privacy</h2><p className="mt-2 text-sm leading-6 text-slate-400">Monitoring targets are validated to reduce SSRF risk, agent requests are authenticated, and secrets are kept out of normal UI/log output. Public status pages expose only monitors explicitly selected for that page.</p><p className="mt-3 text-sm leading-6 text-slate-400">The current product uses an anonymous browser identity rather than a login system. A random anonymous ID is stored in browser storage and linked server-side to an isolated workspace; it does not contain email, phone, name, IP address or device fingerprint data. Clearing site data or using another browser creates a separate identity.</p></div></div></section>
   <div className="mt-12 flex flex-wrap gap-3"><Link href="/dashboard" className="rounded-xl bg-cyan-400 px-5 py-3 font-bold text-slate-950">Open Dashboard</Link><Link href="/status-page" className="rounded-xl border border-slate-700 px-5 py-3 font-semibold">Create Status Page</Link></div>
  </div>
 </main>;
}