"use client";
import Link from "next/link";
import {usePathname} from "next/navigation";
import {Activity,AlertTriangle,Bell,Settings,LayoutDashboard,Globe2,ChevronRight,PanelTop,Info,Menu,Laptop} from "lucide-react";

const nav=[["/dashboard","Dashboard",LayoutDashboard],["/monitors","Monitors",Globe2],["/local-monitor","Local Monitor",Laptop],["/incidents","Incidents",AlertTriangle],["/status-page","Status Pages",PanelTop],["/alerts","Alerts",Bell],["/settings","Settings",Settings]] as const;

export default function Shell({children}:{children:React.ReactNode}){
 const pathname=usePathname();
 return <div className="min-h-screen bg-[#07090d]">
  <aside className="fixed inset-y-0 left-0 z-40 hidden w-[255px] border-r border-[#1d2530] bg-[#0a0d12] md:block"><div className="flex h-full flex-col">
   <div className="flex items-center gap-3 border-b border-[#1d2530] px-6 py-6"><div className="grid h-9 w-9 place-items-center rounded-xl border border-cyan-400/20 bg-cyan-400/10"><Activity className="text-cyan-300" size={20}/></div><div><div className="text-sm font-extrabold tracking-wide">SERVER MONITOR</div><div className="text-[10px] uppercase tracking-[.2em] text-slate-500">Infrastructure</div></div></div>
   <div className="px-4 pt-6"><div className="section-kicker mb-3 px-3">Workspace</div><nav className="space-y-1">{nav.map(([href,label,Icon])=>{const active=pathname===href;return <Link key={href} href={href} className={`group flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-medium transition ${active?"bg-cyan-400/10 text-cyan-300 border border-cyan-400/10":"text-slate-400 hover:bg-white/[.035] hover:text-slate-100"}`}><Icon size={18}/><span>{label}</span>{active&&<ChevronRight size={15} className="ml-auto opacity-70"/>}</Link>})}</nav></div>
   <div className="mt-auto p-4"><Link href="/" className="mb-3 flex items-center gap-2 rounded-lg px-1 text-xs text-slate-500 hover:text-cyan-300"><Info size={14}/> Back Home</Link><Link href="/about" className="mb-3 flex items-center gap-2 px-1 text-xs text-slate-500 hover:text-cyan-300"><Info size={14}/> About SERVER MONITOR</Link><div className="rounded-xl border border-emerald-500/10 bg-emerald-500/[.04] p-3"><div className="flex items-center gap-2 text-xs font-semibold text-emerald-300"><span className="h-2 w-2 rounded-full bg-emerald-400"/>Monitoring engine online</div><div className="mt-1 text-[11px] text-slate-500">Background checks are running</div></div><div className="mt-3 px-1 text-[10px] text-slate-600">SERVER MONITOR v1.0</div></div>
  </div></aside>
  <details className="group sticky top-0 z-50 border-b border-[#1d2530] bg-[#0a0d12]/95 backdrop-blur-xl md:hidden"><summary className="flex h-16 cursor-pointer list-none items-center justify-between px-4 [&::-webkit-details-marker]:hidden"><Link href="/" className="flex items-center gap-2" onClick={(e)=>e.stopPropagation()}><div className="grid h-9 w-9 place-items-center rounded-xl border border-cyan-400/20 bg-cyan-400/10"><Activity className="text-cyan-300" size={19}/></div><div><div className="text-xs font-extrabold tracking-wide">SERVER MONITOR</div><div className="text-[9px] uppercase tracking-[.16em] text-slate-500">Infrastructure</div></div></Link><span className="grid h-10 w-10 place-items-center rounded-xl border border-slate-700 text-slate-200 group-open:bg-cyan-400/10 group-open:text-cyan-300"><Menu size={20}/></span></summary><div className="border-t border-[#202733] bg-[#0a0d12] p-3 shadow-2xl"><nav className="grid grid-cols-2 gap-2">{nav.map(([href,label,Icon])=><Link key={href} href={href} className={`flex items-center gap-2 rounded-xl px-3 py-3 text-sm ${pathname===href?"bg-cyan-400/10 text-cyan-300":"text-slate-400 hover:bg-white/[.035]"}`}><Icon size={17}/>{label}</Link>)}<Link href="/" className="col-span-2 flex items-center justify-center gap-2 rounded-xl border border-cyan-400/20 bg-cyan-400/10 px-3 py-3 text-sm font-semibold text-cyan-300"><Info size={17}/>Back Home</Link><Link href="/about" className="col-span-2 flex items-center gap-2 rounded-xl px-3 py-3 text-sm text-slate-400"><Info size={17}/>About SERVER MONITOR</Link></nav></div></details>
  <main className="min-h-screen md:ml-[255px]"><div className="mx-auto w-full max-w-[1500px] px-3 py-4 sm:px-5 sm:py-5 lg:px-8">{children}</div></main>
 </div>;
}