import {db} from "./db";
import {statusInfo} from "./status-codes";
import {validateMonitorUrl} from "./security";
import tls from "node:tls";
async function sslInfo(host:string,timeoutMs:number){return new Promise<{expiresAt:Date;days:number}|null>(resolve=>{const socket=tls.connect({host,port:443,servername:host,rejectUnauthorized:false,timeout:Math.min(timeoutMs,5000)},()=>{try{const cert=socket.getPeerCertificate();const exp=cert?.valid_to?new Date(cert.valid_to):null;if(!exp||Number.isNaN(exp.getTime())){socket.destroy();return resolve(null);}resolve({expiresAt:exp,days:Math.floor((exp.getTime()-Date.now())/86400000)});}catch{resolve(null)}finally{socket.destroy();}});socket.on("error",()=>resolve(null));socket.on("timeout",()=>{socket.destroy();resolve(null)});});}
async function requestWithSafeRedirect(start:URL,m:any){let url=start;for(let i=0;i<5;i++){const r=await fetch(url,{method:m.method,headers:(m.headers as Record<string,string>|null)??{},body:m.method==="GET"||m.method==="HEAD"?undefined:m.requestBody??undefined,signal:AbortSignal.timeout(m.timeoutMs),redirect:"manual"});if(r.status<300||r.status>=400)return r;const location=r.headers.get("location");if(!location) return r;url=await validateMonitorUrl(new URL(location,url).toString());}throw new Error("Too many redirects.");}
export async function checkMonitor(id:string){const m=await db.monitor.findUnique({where:{id}});if(!m)throw new Error("Monitor not found");const started=Date.now();let status:"UP"|"DOWN"|"DEGRADED"="DOWN";let httpStatus:number|undefined,failureType:any,failureMessage:string|undefined,name:string|undefined,explanation:string|undefined,sslExpiresAt:Date|undefined,sslDaysRemaining:number|undefined;
 try{const url=await validateMonitorUrl(m.url);if(url.protocol==="https:"){const ssl=await sslInfo(url.hostname,m.timeoutMs);if(ssl){sslExpiresAt=ssl.expiresAt;sslDaysRemaining=ssl.days;if(ssl.days<0)failureMessage="SSL certificate has expired.";else if(ssl.days<=14)failureMessage=`SSL certificate expires in ${ssl.days} days.`;}}
  const r=await requestWithSafeRedirect(url,m);httpStatus=r.status;const info=statusInfo(r.status);name=info.name;explanation=info.explanation;status=r.status===m.expectedStatus?"UP":(r.status>=500?"DOWN":"DEGRADED");if(sslDaysRemaining!=null&&sslDaysRemaining<0)status="DOWN";
 }catch(e:any){const msg=String(e?.message||"Request failed");if(e?.name==="TimeoutError"||/timeout/i.test(msg))failureType="TIMEOUT";else if(e?.code==="ENOTFOUND"||/getaddrinfo|dns/i.test(msg))failureType="DNS";else if(/certificate|tls|ssl/i.test(msg))failureType="TLS";else if(e?.code==="ECONNREFUSED"||/connection refused/i.test(msg))failureType="CONNECTION_REFUSED";else failureType="NETWORK";failureMessage=msg;}
 const responseTimeMs=Date.now()-started;const check=await db.monitorCheck.create({data:{monitorId:id,status,httpStatus,statusName:name,statusExplanation:explanation,responseTimeMs,failureType,failureMessage,sslExpiresAt,sslDaysRemaining}});await db.monitor.update({where:{id},data:{status,lastCheckedAt:check.checkedAt,nextCheckAt:new Date(Date.now()+m.intervalSeconds*1000)}});return check;}
