"use client";
import {useEffect,useState} from "react";
import Shell from "@/components/Shell";
const FIXED_FROM="onboarding@resend.dev";
const FIXED_NAME="SERVER MONITOR";
export default function SettingsPage(){
 const [email,setEmail]=useState("");const [enabled,setEnabled]=useState(true);const [connected,setConnected]=useState(false);const [saved,setSaved]=useState(false);const [testing,setTesting]=useState(false);const [msg,setMsg]=useState("");
 useEffect(()=>{fetch("/api/settings").then(r=>r.json()).then(d=>{setEmail(d.email??"");setEnabled(d.emailAlerts!=="false");setConnected(Boolean(d.connected));const p=new URLSearchParams(location.search);if(p.get("resend")==="connected")setMsg("✓ Resend connected successfully.");if(p.get("resend")==="error")setMsg("✕ Resend connection was not completed.");}).catch(()=>{});},[]);
 async function save(){setSaved(false);setMsg("");const r=await fetch("/api/settings",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email,emailAlerts:enabled,provider:"resend",fromEmail:FIXED_FROM,fromName:FIXED_NAME})});const d=await r.json();if(r.ok)setSaved(true);else setMsg(d.error||"Could not save settings");}
 async function testEmail(){setTesting(true);setMsg("");const r=await fetch("/api/settings/test-email",{method:"POST"});const x=await r.json();setMsg(r.ok?"✓ "+x.message:"✕ "+(x.error||"Test failed"));setTesting(false);}
 return <Shell><div className="max-w-3xl space-y-6"><div><h1 className="text-2xl font-bold">Settings</h1><p className="text-slate-400">Complete notification and email provider setup from the dashboard.</p></div>
 <div className="rounded-xl border border-slate-800 bg-slate-900/70 p-6 space-y-5"><div><div className="text-sm font-semibold">Notification recipient</div><p className="text-xs text-slate-500 mt-1">This workspace's monitoring alerts will be sent here.</p><input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="you@example.com" className="mt-3 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 outline-none"/></div>
 <label className="flex items-center gap-3"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/><span>Enable email alert notifications</span></label>
 <div className="border-t border-slate-800 pt-5"><div className="flex items-center justify-between gap-3"><div><div className="text-sm font-semibold">Email provider</div><p className="text-xs text-slate-500 mt-1">Resend is securely connected for email delivery.</p></div><span className={`rounded-full px-3 py-1 text-xs font-semibold ${connected?"bg-emerald-400/10 text-emerald-400":"bg-amber-400/10 text-amber-400"}`}>{connected?"Connected":"Not connected"}</span></div>
 {!connected?<button onClick={()=>{location.href="/api/settings/resend/connect"}} className="mt-4 rounded-lg bg-cyan-500 px-4 py-2 font-semibold text-slate-950">Connect Resend</button>:<div className="mt-4 rounded-lg border border-emerald-500/20 bg-emerald-500/5 p-4 text-sm text-emerald-300">Resend is connected to this workspace. Email credentials stay server-side.</div>}
 <div className="grid md:grid-cols-2 gap-3 mt-4"><div className="text-sm">From email<div className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-slate-300">{FIXED_FROM}</div></div><div className="text-sm">From name<div className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-slate-300">{FIXED_NAME}</div></div></div>
 <div className="mt-4 rounded-lg border border-slate-700 bg-slate-950 p-3 text-xs text-slate-400">Test sender: <span className="text-slate-200">{FIXED_FROM}</span> · Sender name: <span className="text-slate-200">{FIXED_NAME}</span></div></div>
 <div className="flex flex-wrap items-center gap-3"><button onClick={save} className="rounded-lg bg-cyan-500 px-4 py-2 font-semibold text-slate-950">Save settings</button><button onClick={testEmail} disabled={testing||!email||!connected} className="rounded-lg border border-cyan-500/50 px-4 py-2 disabled:opacity-40">{testing?"Sending…":"Send Test Email"}</button>{saved&&<span className="text-emerald-400">Saved</span>}{msg&&<span className="text-sm">{msg}</span>}</div></div></div></Shell>;
}
